name: ra_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  date_picker_timeline: ^1.2.6
  flutter_local_notifications: ^17.2.4
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.11
  get: ^4.6.6
  get_storage: ^2.1.1
  sqflite: ^2.4.0
  google_fonts: ^6.2.1
  sqflite_common_ffi: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
